export const EDIT_USER = 'EDIT_USER';
export const SET_EVENT = 'SET_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const REMOVE_EVENT ='REMOVE_EVENT';
export const CUR_EVENT ='CUR_EVENT';
export const SAVE_FRIENDS = 'SAVE_FRIENDS';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const REJECT_FRIEND = 'REJECT_FRIEND';